import BesovSpacesGoodGrid.GoodGrid.BesovAtoms
import BesovSpacesGoodGrid.GoodGrid.Multipliers.Definition
import BesovSpacesGoodGrid.GoodGrid.Multipliers.Besovspq
import Mathlib.Probability.Martingale.Convergence

/-!
# The `selfs` class is bounded

This file contains the first quantitative step in the proof that Souza
`selfs` multipliers are essentially bounded: a `selfs` bound controls the
ambient `L^p` norm of the product with every normalized Souza atom.
-/

open scoped ENNReal Topology
open MeasureTheory

namespace GoodGridSpace

universe u

variable {α : Type u} [MeasurableSpace α]

noncomputable section

/--
The root good-grid cell, namely the unique level-zero cell `univ`.
-/
def rootGoodGridCell (G : GoodGridSpace (α := α)) : GoodGridCell G where
  level := 0
  cell := Set.univ
  mem := by
    simp [G.grid.grid.first_partition_eq_univ]

/--
The sigma-algebra generated by the `n`-th good-grid partition.
-/
@[reducible] def goodGridLevelMeasurableSpace (G : GoodGridSpace (α := α)) (n : ℕ) :
    MeasurableSpace α :=
  MeasurableSpace.generateFrom ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α))

/--
Each good-grid level is measurable with respect to the next one.

The proof uses the nested partition structure: a parent cell is the finite union
of its children at the next level, and those children are generators at level
`n + 1`.
-/
theorem goodGridLevelMeasurableSpace_mono_succ
    (G : GoodGridSpace (α := α)) (n : ℕ) :
    goodGridLevelMeasurableSpace G n ≤ goodGridLevelMeasurableSpace G (n + 1) := by
  classical
  refine MeasurableSpace.generateFrom_le ?_
  intro Q hQ
  have hQ_eq :
      Q = ⋃ P ∈ G.grid.childrenFinset n Q, P := by
    ext x
    constructor
    · intro hxQ
      rcases Set.mem_iUnion.1 (G.grid.covering_by_children n Q hQ hxQ) with ⟨P, hP⟩
      rcases Set.mem_iUnion.1 hP with ⟨hPchild, hxP⟩
      exact Set.mem_iUnion.2
        ⟨P, Set.mem_iUnion.2
          ⟨(G.grid.mem_childrenFinset_iff n Q P).2 hPchild, hxP⟩⟩
    · intro hx
      rcases Set.mem_iUnion.1 hx with ⟨P, hxP⟩
      rcases Set.mem_iUnion.1 hxP with ⟨hPfin, hxPmem⟩
      exact ((G.grid.mem_childrenFinset_iff n Q P).1 hPfin).2 hxPmem
  rw [hQ_eq]
  exact Finset.measurableSet_biUnion (G.grid.childrenFinset n Q) fun P hP =>
    MeasurableSpace.measurableSet_generateFrom
      ((G.grid.mem_childrenFinset_iff n Q P).1 hP).1

/--
The cells of one good-grid level form a pi-system.
-/
theorem isPiSystem_goodGridLevelCells
    (G : GoodGridSpace (α := α)) (n : ℕ) :
    IsPiSystem ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α)) := by
  intro Q hQ R hR hQR
  by_cases h_eq : Q = R
  · rw [h_eq]
    simpa using hR
  · exfalso
    have hdisj : Disjoint Q R :=
      G.grid.grid.disjoint n Q R hQ hR h_eq
    exact hQR.ne_empty (Set.disjoint_iff_inter_eq_empty.mp hdisj)

/--
The filtration generated by the good-grid partitions.
-/
def goodGridFiltration (G : GoodGridSpace (α := α)) :
    Filtration ℕ ‹MeasurableSpace α› where
  seq n := goodGridLevelMeasurableSpace G n
  mono' := monotone_nat_of_le_succ (goodGridLevelMeasurableSpace_mono_succ G)
  le' := by
    intro n
    change MeasurableSpace.generateFrom
      ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α)) ≤ ‹MeasurableSpace α›
    have hle :
        MeasurableSpace.generateFrom
            ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α)) ≤
          ⨆ k : ℕ, MeasurableSpace.generateFrom
            ((G.grid.grid.partitions k : Finset (Set α)) : Set (Set α)) :=
      le_iSup
        (fun k : ℕ => MeasurableSpace.generateFrom
          ((G.grid.grid.partitions k : Finset (Set α)) : Set (Set α))) n
    have hgen :
        (⨆ k : ℕ, MeasurableSpace.generateFrom
          ((G.grid.grid.partitions k : Finset (Set α)) : Set (Set α))) =
          ‹MeasurableSpace α› :=
      G.grid.grid.generates
    exact hle.trans (le_of_eq hgen)

/--
The good-grid filtration generates the ambient measurable space.
-/
theorem iSup_goodGridFiltration (G : GoodGridSpace (α := α)) :
    ⨆ n : ℕ, goodGridFiltration G n = ‹MeasurableSpace α› := by
  change ⨆ n : ℕ, MeasurableSpace.generateFrom
    ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α)) = ‹MeasurableSpace α›
  exact G.grid.grid.generates

/--
Levy's upward theorem specialized to the good-grid filtration.
-/
theorem tendsto_ae_condExp_goodGridFiltration
    (G : GoodGridSpace (α := α)) (f : α → ℝ) :
    ∀ᵐ x ∂G.grid.μ,
      Filter.Tendsto
        (fun n => (G.grid.μ[f | goodGridFiltration G n]) x)
        Filter.atTop
        (𝓝 ((G.grid.μ[f | ⨆ n : ℕ, goodGridFiltration G n]) x)) := by
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  exact MeasureTheory.tendsto_ae_condExp
    (ℱ := goodGridFiltration G) (μ := G.grid.μ) f

/--
For an integrable function, good-grid conditional expectations converge to the
function itself, because the good-grid filtration generates the ambient
sigma-algebra.
-/
theorem Integrable.tendsto_ae_condExp_goodGridFiltration
    (G : GoodGridSpace (α := α)) {f : α → ℝ}
    (hf : Integrable f G.grid.μ)
    (hfm : StronglyMeasurable f) :
    ∀ᵐ x ∂G.grid.μ,
      Filter.Tendsto
        (fun n => (G.grid.μ[f | goodGridFiltration G n]) x)
        Filter.atTop
        (𝓝 (f x)) := by
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  have hfmeas : StronglyMeasurable[⨆ n : ℕ, goodGridFiltration G n] f := by
    rw [iSup_goodGridFiltration G]
    exact hfm
  exact hf.tendsto_ae_condExp (ℱ := goodGridFiltration G) hfmeas

/--
For an integrable function, good-grid conditional expectations converge to the
function itself almost everywhere.  This version uses the strongly measurable
representative supplied by `AEStronglyMeasurable`, so it does not require a
separate strong-measurability hypothesis.
-/
theorem Integrable.tendsto_ae_condExp_goodGridFiltration'
    (G : GoodGridSpace (α := α)) {f : α → ℝ}
    (hf : Integrable f G.grid.μ) :
    ∀ᵐ x ∂G.grid.μ,
      Filter.Tendsto
        (fun n => (G.grid.μ[f | goodGridFiltration G n]) x)
        Filter.atTop
        (𝓝 (f x)) := by
  let f' := hf.aestronglyMeasurable.mk f
  have hf_ae : f =ᵐ[G.grid.μ] f' :=
    hf.aestronglyMeasurable.ae_eq_mk
  have hf'_int : Integrable f' G.grid.μ :=
    hf.congr hf_ae
  have hf'_strong : StronglyMeasurable f' :=
    hf.aestronglyMeasurable.stronglyMeasurable_mk
  have htend :=
    Integrable.tendsto_ae_condExp_goodGridFiltration
      (G := G) hf'_int hf'_strong
  have hcondExp :
      ∀ᵐ x ∂G.grid.μ,
        ∀ n, G.grid.μ[f | goodGridFiltration G n] x =
          G.grid.μ[f' | goodGridFiltration G n] x := by
    refine ae_all_iff.2 ?_
    intro n
    exact condExp_congr_ae (μ := G.grid.μ)
      (m := goodGridFiltration G n) hf_ae
  filter_upwards [htend, hcondExp, hf_ae] with x hx_tend hx_cond hx_f
  have hseq :
      (fun n => G.grid.μ[f | goodGridFiltration G n] x) =
        fun n => G.grid.μ[f' | goodGridFiltration G n] x := by
    funext n
    exact hx_cond n
  rw [hseq, hx_f]
  exact hx_tend

/--
The step function whose value on a level-`n` cell is the average of `f` over
that cell.
-/
def goodGridLevelAverage (G : GoodGridSpace (α := α)) (f : α → ℝ) (n : ℕ) :
    α → ℝ := by
  classical
  exact fun x => (G.grid.grid.partitions n).sum fun cell =>
    cell.indicator
      (fun _ => ((G.grid.μ cell).toReal)⁻¹ * ∫ y in cell, f y ∂G.grid.μ) x

/--
On a level-`n` cell, the level-average step function is the constant average
over that cell.
-/
theorem goodGridLevelAverage_eq_on_cell
    (G : GoodGridSpace (α := α)) (f : α → ℝ) (n : ℕ)
    {Q : Set α} (hQ : Q ∈ G.grid.grid.partitions n) {x : α} (hxQ : x ∈ Q) :
    goodGridLevelAverage G f n x =
      ((G.grid.μ Q).toReal)⁻¹ * ∫ y in Q, f y ∂G.grid.μ := by
  classical
  unfold goodGridLevelAverage
  rw [Finset.sum_eq_single Q]
  · simp [Set.indicator_of_mem hxQ]
  · intro R hR hRQ
    have hxR_not : x ∉ R := by
      intro hxR
      have hdisj : Disjoint R Q :=
        G.grid.grid.disjoint n R Q hR hQ hRQ
      exact (Set.disjoint_left.mp hdisj hxR hxQ).elim
    simp [Set.indicator_of_notMem hxR_not]
  · intro hQ_not
    exact (hQ_not hQ).elim

/--
The level-average step function has the same integral as `f` on each generator
cell of that level.
-/
theorem setIntegral_goodGridLevelAverage_eq_setIntegral_cell
    (G : GoodGridSpace (α := α)) (f : α → ℝ) (n : ℕ)
    {Q : Set α} (hQ : Q ∈ G.grid.grid.partitions n) :
    ∫ x in Q, goodGridLevelAverage G f n x ∂G.grid.μ =
      ∫ x in Q, f x ∂G.grid.μ := by
  classical
  let μQ : ℝ := (G.grid.μ Q).toReal
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  have hQm : MeasurableSet Q := G.grid.grid.measurable n Q hQ
  have hμQ_pos : 0 < μQ := by
    exact ENNReal.toReal_pos (G.grid.positive_measure n Q hQ).ne'
      (measure_ne_top G.grid.μ Q)
  calc
    ∫ x in Q, goodGridLevelAverage G f n x ∂G.grid.μ
        = ∫ x in Q, (fun _ => μQ⁻¹ * ∫ y in Q, f y ∂G.grid.μ) x ∂G.grid.μ := by
            refine setIntegral_congr_ae hQm ?_
            exact Filter.Eventually.of_forall fun x hx =>
              by simpa [μQ] using goodGridLevelAverage_eq_on_cell G f n hQ hx
    _ = μQ * (μQ⁻¹ * ∫ y in Q, f y ∂G.grid.μ) := by
            rw [setIntegral_const, smul_eq_mul]
            simp [μQ, measureReal_def]
    _ = ∫ y in Q, f y ∂G.grid.μ := by
            field_simp [hμQ_pos.ne']

/--
The finite-level average is measurable with respect to the sigma-algebra
generated by the cells of that level.
-/
theorem stronglyMeasurable_goodGridLevelAverage
    (G : GoodGridSpace (α := α)) (f : α → ℝ) (n : ℕ) :
    StronglyMeasurable[goodGridLevelMeasurableSpace G n]
      (goodGridLevelAverage G f n) := by
  classical
  simpa [goodGridLevelAverage] using
    (G.grid.grid.partitions n).stronglyMeasurable_fun_sum fun Q hQ =>
      (stronglyMeasurable_const.indicator
        (MeasurableSpace.measurableSet_generateFrom hQ :
          MeasurableSet[goodGridLevelMeasurableSpace G n] Q))

/--
The finite-level average is integrable on the ambient finite-measure grid.
-/
theorem integrable_goodGridLevelAverage
    (G : GoodGridSpace (α := α)) (f : α → ℝ) (n : ℕ) :
    Integrable (goodGridLevelAverage G f n) G.grid.μ := by
  classical
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  simpa [goodGridLevelAverage] using
    integrable_finsetSum (G.grid.grid.partitions n) fun Q hQ =>
      Integrable.indicator
        (integrable_const
          (((G.grid.μ Q).toReal)⁻¹ * ∫ y in Q, f y ∂G.grid.μ))
        (G.grid.grid.measurable n Q hQ)

/--
The finite-level average and the original integrable function have the same
integral on every measurable set of that level.
-/
theorem setIntegral_goodGridLevelAverage_eq_setIntegral
    (G : GoodGridSpace (α := α)) {f : α → ℝ} (n : ℕ)
    (hf : Integrable f G.grid.μ) {s : Set α}
    (hs : MeasurableSet[goodGridLevelMeasurableSpace G n] s) :
    ∫ x in s, goodGridLevelAverage G f n x ∂G.grid.μ =
      ∫ x in s, f x ∂G.grid.μ := by
  classical
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  let avg := goodGridLevelAverage G f n
  have havg_int : Integrable avg G.grid.μ :=
    integrable_goodGridLevelAverage G f n
  have hcell_disj :
      Set.Pairwise ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α))
        (Function.onFun Disjoint fun Q : Set α => Q) := by
    intro Q hQ R hR hQR
    exact G.grid.grid.disjoint n Q R hQ hR hQR
  have hcover :
      (⋃ Q ∈ G.grid.grid.partitions n, Q) = (Set.univ : Set α) :=
    G.grid.grid.covering n
  have havg_total :
      ∫ x, avg x ∂G.grid.μ = ∫ x, f x ∂G.grid.μ := by
    calc
      ∫ x, avg x ∂G.grid.μ
          = ∫ x in (Set.univ : Set α), avg x ∂G.grid.μ :=
              (setIntegral_univ (μ := G.grid.μ) (f := avg)).symm
      _ = ∫ x in ⋃ Q ∈ G.grid.grid.partitions n, Q, avg x ∂G.grid.μ := by
              rw [hcover]
      _ = ∑ Q ∈ G.grid.grid.partitions n,
            ∫ x in Q, avg x ∂G.grid.μ := by
              exact integral_biUnion_finset
                (t := G.grid.grid.partitions n) (s := fun Q : Set α => Q)
                (μ := G.grid.μ) (f := avg)
                (fun Q hQ => G.grid.grid.measurable n Q hQ)
                hcell_disj
                (fun Q hQ => havg_int.integrableOn)
      _ = ∑ Q ∈ G.grid.grid.partitions n,
            ∫ x in Q, f x ∂G.grid.μ :=
              Finset.sum_congr rfl fun Q hQ =>
                setIntegral_goodGridLevelAverage_eq_setIntegral_cell G f n hQ
      _ = ∫ x in ⋃ Q ∈ G.grid.grid.partitions n, Q, f x ∂G.grid.μ := by
              exact (integral_biUnion_finset
                (t := G.grid.grid.partitions n) (s := fun Q : Set α => Q)
                (μ := G.grid.μ) (f := f)
                (fun Q hQ => G.grid.grid.measurable n Q hQ)
                hcell_disj
                (fun Q hQ => hf.integrableOn)).symm
      _ = ∫ x in (Set.univ : Set α), f x ∂G.grid.μ := by
              rw [hcover]
      _ = ∫ x, f x ∂G.grid.μ :=
              setIntegral_univ (μ := G.grid.μ) (f := f)
  change ∫ x in s, avg x ∂G.grid.μ = ∫ x in s, f x ∂G.grid.μ
  induction s, hs using
    MeasurableSpace.induction_on_inter
      (m := goodGridLevelMeasurableSpace G n)
      (s := ((G.grid.grid.partitions n : Finset (Set α)) : Set (Set α)))
      rfl
      (isPiSystem_goodGridLevelCells G n)
    with
  | empty =>
      simp
  | basic Q hQ =>
      exact setIntegral_goodGridLevelAverage_eq_setIntegral_cell G f n hQ
  | compl t ht h_eq =>
      have ht_ambient : MeasurableSet t := (goodGridFiltration G).le n t ht
      have havg_compl :=
        integral_add_compl (μ := G.grid.μ) (f := avg) ht_ambient havg_int
      have hf_compl :=
        integral_add_compl (μ := G.grid.μ) (f := f) ht_ambient hf
      linarith
  | iUnion t ht_disj ht_meas h_eq =>
      have ht_meas_ambient : ∀ i, MeasurableSet (t i) := fun i =>
        (goodGridFiltration G).le n (t i) (ht_meas i)
      calc
        ∫ x in ⋃ i, t i, avg x ∂G.grid.μ
            = ∑' i, ∫ x in t i, avg x ∂G.grid.μ := by
                exact integral_iUnion (μ := G.grid.μ) (f := avg)
                  ht_meas_ambient ht_disj havg_int.integrableOn
        _ = ∑' i, ∫ x in t i, f x ∂G.grid.μ := by
                simp [h_eq]
        _ = ∫ x in ⋃ i, t i, f x ∂G.grid.μ := by
                exact (integral_iUnion (μ := G.grid.μ) (f := f)
                  ht_meas_ambient ht_disj hf.integrableOn).symm

/--
The finite-level cell average is the conditional expectation onto the
corresponding good-grid level.
-/
theorem goodGridLevelAverage_ae_eq_condExp
    (G : GoodGridSpace (α := α)) {f : α → ℝ} (n : ℕ)
    (hf : Integrable f G.grid.μ) :
    goodGridLevelAverage G f n =ᵐ[G.grid.μ]
      G.grid.μ[f | goodGridFiltration G n] := by
  classical
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  let avg := goodGridLevelAverage G f n
  have hm : goodGridFiltration G n ≤ ‹MeasurableSpace α› :=
    (goodGridFiltration G).le n
  refine ae_eq_condExp_of_forall_setIntegral_eq (μ := G.grid.μ) hm hf ?_ ?_ ?_
  · intro s _hs _hμs
    exact (integrable_goodGridLevelAverage G f n).integrableOn
  · intro s hs _hμs
    exact setIntegral_goodGridLevelAverage_eq_setIntegral G n hf hs
  · exact (stronglyMeasurable_goodGridLevelAverage G f n).aestronglyMeasurable

/--
If all level-`n` cell averages of a real function are bounded by `M`, then the
level-average step function is pointwise bounded by `M`.
-/
theorem goodGridLevelAverage_le_of_cellIntegral_le
    (G : GoodGridSpace (α := α)) (f : α → ℝ) (n : ℕ) {M : ℝ}
    (hcell :
      ∀ Q : Set α, Q ∈ G.grid.grid.partitions n →
        ∫ y in Q, f y ∂G.grid.μ ≤ (G.grid.μ Q).toReal * M) :
    ∀ x, goodGridLevelAverage G f n x ≤ M := by
  classical
  intro x
  have hxcover : x ∈ ⋃ Q ∈ G.grid.grid.partitions n, Q := by
    rw [G.grid.grid.covering n]
    exact Set.mem_univ x
  rcases Set.mem_iUnion.1 hxcover with ⟨Q, hQcover⟩
  rcases Set.mem_iUnion.1 hQcover with ⟨hQ, hxQ⟩
  let μQ : ℝ := (G.grid.μ Q).toReal
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  have hμQ_pos : 0 < μQ := by
    exact ENNReal.toReal_pos (G.grid.positive_measure n Q hQ).ne'
      (measure_ne_top G.grid.μ Q)
  calc
    goodGridLevelAverage G f n x
        = Q.indicator
            (fun _ => ((G.grid.μ Q).toReal)⁻¹ * ∫ y in Q, f y ∂G.grid.μ) x := by
          unfold goodGridLevelAverage
          rw [Finset.sum_eq_single Q]
          · intro R hR hRQ
            have hxR_not : x ∉ R := by
              intro hxR
              have hdisj : Disjoint R Q :=
                G.grid.grid.disjoint n R Q hR hQ hRQ
              exact (Set.disjoint_left.mp hdisj hxR hxQ).elim
            simp [Set.indicator_of_notMem hxR_not]
          · intro hQ_not
            exact (hQ_not hQ).elim
    _ = μQ⁻¹ * ∫ y in Q, f y ∂G.grid.μ := by
          simp [Set.indicator_of_mem hxQ, μQ]
    _ ≤ μQ⁻¹ * (μQ * M) := by
          exact mul_le_mul_of_nonneg_left (hcell Q hQ) (inv_nonneg.mpr hμQ_pos.le)
    _ = M := by
          field_simp [hμQ_pos.ne']

/--
Martingale convergence turns uniform bounds for the finite-level cell averages
into an almost-everywhere bound for the limiting function.

This is the final abstract step in the `selfs ⊂ L∞` argument: once the
finite-level average is identified a.e. with the conditional expectation
`E(f | 𝓕ₙ)`, Levy's theorem sends those averages to `f`.
-/
theorem ae_le_of_goodGridLevelAverage_le_of_ae_eq_condExp
    (G : GoodGridSpace (α := α)) {f : α → ℝ} {M : ℝ}
    (hf : Integrable f G.grid.μ)
    (havg_le : ∀ n x, goodGridLevelAverage G f n x ≤ M)
    (havg_eq_condExp :
      ∀ n, goodGridLevelAverage G f n =ᵐ[G.grid.μ]
        G.grid.μ[f | goodGridFiltration G n]) :
    ∀ᵐ x ∂G.grid.μ, f x ≤ M := by
  have htend :=
    Integrable.tendsto_ae_condExp_goodGridFiltration'
      (G := G) hf
  have hcondExp_le :
      ∀ n, ∀ᵐ x ∂G.grid.μ, G.grid.μ[f | goodGridFiltration G n] x ≤ M := by
    intro n
    filter_upwards [havg_eq_condExp n] with x hx
    rw [← hx]
    exact havg_le n x
  have hcondExp_le_all :
      ∀ᵐ x ∂G.grid.μ, ∀ n, G.grid.μ[f | goodGridFiltration G n] x ≤ M :=
    ae_all_iff.2 hcondExp_le
  filter_upwards [htend, hcondExp_le_all] with x hx_tend hx_le
  exact le_of_tendsto hx_tend (Filter.Eventually.of_forall hx_le)

/--
Martingale convergence turns uniform bounds for the finite-level cell averages
into an almost-everywhere bound for the original function.

This version uses the already-proved identification of the finite cell average
with conditional expectation.
-/
theorem ae_le_of_goodGridLevelAverage_le
    (G : GoodGridSpace (α := α)) {f : α → ℝ} {M : ℝ}
    (hf : Integrable f G.grid.μ)
    (havg_le : ∀ n x, goodGridLevelAverage G f n x ≤ M) :
    ∀ᵐ x ∂G.grid.μ, f x ≤ M :=
  ae_le_of_goodGridLevelAverage_le_of_ae_eq_condExp
    G hf havg_le fun n => goodGridLevelAverage_ae_eq_condExp G n hf

/--
Hölder on one good-grid cell, expressed as a comparison between the local
`L¹` and `L^p` seminorms of a cell indicator.
-/
theorem eLpNorm_one_cellIndicator_le_eLpNorm_mul_measure_rpow
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (p : ℝ≥0∞) (hp : 1 ≤ p)
    {m : α → ℂ}
    (hm : MemLp (Q.cell.indicator m) p G.grid.μ) :
    eLpNorm (Q.cell.indicator m) 1 G.grid.μ ≤
      eLpNorm (Q.cell.indicator m) p G.grid.μ *
        (G.grid.μ Q.cell) ^ (1 - 1 / p.toReal) := by
  classical
  have hQm : MeasurableSet Q.cell := G.grid.grid.measurable Q.level Q.cell Q.mem
  have hm_restrict : MemLp m p (G.grid.μ.restrict Q.cell) := by
    simpa [hQm] using
      (memLp_indicator_iff_restrict (μ := G.grid.μ) (p := p)
        (s := Q.cell) (f := m) hQm).1 hm
  have hholder :=
    eLpNorm_le_eLpNorm_mul_rpow_measure_univ
      (μ := G.grid.μ.restrict Q.cell) (f := m)
      (p := (1 : ℝ≥0∞)) (q := p) hp hm_restrict.1
  rw [← eLpNorm_indicator_eq_eLpNorm_restrict hQm,
    ← eLpNorm_indicator_eq_eLpNorm_restrict hQm,
    Measure.restrict_apply MeasurableSet.univ, Set.univ_inter,
    ENNReal.toReal_one] at hholder
  simpa using hholder

/--
The constant in the Souza Besov embedding into the ambient `L^p` space.

For a good grid the overlap constant is definitionally `1`, but we keep the
same expression as the abstract weak-grid embedding so this result can be
reused without unfolding that implementation detail.
-/
noncomputable def souzaBesovLpEmbeddingConstant
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞) : ℝ :=
  ((G.toWeakGridSpace.grid.Cmult1 : ℝ) ^ (1 + 1 / p.toReal)) *
    WeakGridSpace.LpGridRepresentation.cCoefficient p q
      (fun k =>
        (WeakGridSpace.LpGridRepresentation.levelMeasureWeight
          G.toWeakGridSpace s p p k) ^ p.toReal)

/--
The local `L^p` embedding constant for the Souza Besov space on the grid
induced by a cell.
-/
noncomputable def inducedSouzaBesovLpEmbeddingConstant
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞) : ℝ :=
  let Wi := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell
  ((Wi.grid.Cmult1 : ℝ) ^ (1 + 1 / p.toReal)) *
    WeakGridSpace.LpGridRepresentation.cCoefficient p q
      (fun k =>
        (WeakGridSpace.LpGridRepresentation.levelMeasureWeight
          Wi s p p k) ^ p.toReal)

/--
The uniform geometric constant controlling all induced `L^p` embeddings on
good-grid cells.

The induced-grid constant itself carries a factor `μ(Q)^s`; this definition is
the part that does not depend on the cell.
-/
noncomputable def souzaBesovLpLocalEmbeddingConstant
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞) : ℝ :=
  WeakGridSpace.LpGridRepresentation.cCoefficient p q
    (besovAtomGeometricWeight G s p)

/--
The induced Souza embedding constant has the expected cell scale.
-/
theorem inducedSouzaBesovLpEmbeddingConstant_le_cellScale
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)] :
    inducedSouzaBesovLpEmbeddingConstant G Q s p q ≤
      (G.grid.μ Q.cell).toReal ^ s *
        souzaBesovLpLocalEmbeddingConstant G s p q := by
  classical
  let Wi := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell
  let Cind : ℝ :=
    WeakGridSpace.LpGridRepresentation.cCoefficient p q
      (fun k =>
        (WeakGridSpace.LpGridRepresentation.levelMeasureWeight Wi s p p k) ^ p.toReal)
  let Cgeom : ℝ :=
    WeakGridSpace.LpGridRepresentation.cCoefficient p q
      (besovAtomGeometricWeight G s p)
  let M : ℝ := (G.grid.μ Q.cell).toReal ^ s
  have hCemb_one :
      ((Wi.grid.Cmult1 : ℝ) ^ (1 + 1 / p.toReal)) = 1 := by
    dsimp [Wi, WeakGridSpace.inducedWeakGridSpace, WeakGridSpace.inducedWeakGrid,
      GoodGridSpace.toWeakGridSpace, GoodGridSpace.toWeakGrid]
    norm_num
  have hCind_le : Cind ≤ M * Cgeom := by
    simpa [Wi, Cind, Cgeom, M] using
      GoodGridSpace.induced_cCoefficient_le_geometric
        G Q s p q hs (inferInstance : Fact (1 ≤ p)) hp_top
  calc
    inducedSouzaBesovLpEmbeddingConstant G Q s p q
        = Cind := by
          dsimp [inducedSouzaBesovLpEmbeddingConstant, Cind]
          rw [hCemb_one]
          ring
    _ ≤ M * Cgeom := hCind_le
    _ = (G.grid.μ Q.cell).toReal ^ s *
        souzaBesovLpLocalEmbeddingConstant G s p q := by
          rfl

/--
The canonical Souza atom on a good-grid cell is an admissible `selfs` test.

The statement also records the concrete function represented by the chosen
`L^p` element, which is the bridge needed to turn the atom test into estimates
on cell indicators.
-/
theorem exists_canonicalSouzaAtomicUnit
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (Q : GoodGridCell G) :
    ∃ x : WeakGridSpace.BesovishSpace
        (souzaAtomFamily G s p hs hp hp_top) q,
      WeakGridSpace.AtomicUnit
        (A := souzaAtomFamily G s p hs hp hp_top) q x ∧
      WeakGridSpace.RepresentsFunction
        (G := G.toWeakGridSpace) (p := p)
        (canonicalSouzaAtom G s p Q)
        (x : Lp ℂ p G.toWeakGridSpace.measure) := by
  classical
  let A := souzaAtomFamily G s p hs hp hp_top
  let c : ℂ := (((G.grid.μ Q.cell).toReal ^ (s - (p.toReal)⁻¹) : ℝ) : ℂ)
  let xLp : Lp ℂ p G.toWeakGridSpace.measure :=
    MeasureTheory.indicatorConstLp (μ := G.toWeakGridSpace.measure) p
      (G.grid.grid.measurable Q.level Q.cell Q.mem)
      (GoodGridCell.measure_ne_top Q) c
  have hx_mem : xLp ∈ SouzaBesovSpace G s p q hs hp hp_top := by
    simpa [xLp, c] using
      indicatorConstLp_cell_mem_souzaBesov G s p q hs hp hp_top Q c
  let x : WeakGridSpace.BesovishSpace A q := ⟨xLp, by
    simpa [A, SouzaBesovSpace] using hx_mem⟩
  refine ⟨x, ?_, ?_⟩
  · refine ⟨Q.toWeakGridCell, c, ?_, ?_⟩
    · have hc_nonneg :
          0 ≤ (G.grid.μ Q.cell).toReal ^ (s - (p.toReal)⁻¹) :=
        Real.rpow_nonneg ENNReal.toReal_nonneg _
      change ‖c‖ ≤ (G.grid.μ Q.cell).toReal ^ (s - (p.toReal)⁻¹)
      simp [c, Complex.norm_real, Real.norm_of_nonneg hc_nonneg]
    · have hxcoe :
          ((xLp : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
            =ᵐ[G.toWeakGridSpace.measure] Q.cell.indicator (fun _ => c) :=
        MeasureTheory.indicatorConstLp_coeFn (μ := G.toWeakGridSpace.measure)
          (p := p) (hs := G.grid.grid.measurable Q.level Q.cell Q.mem)
          (hμs := GoodGridCell.measure_ne_top Q) (c := c)
      simpa [WeakGridSpace.RepresentsFunction, A, WeakGridSpace.AtomFamily.toFunction,
        souzaAtomFamily, souzaLocalVectorSpace, GoodGridCell.toWeakGridCell, x] using hxcoe
  · have hxcoe :
        ((xLp : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
          =ᵐ[G.toWeakGridSpace.measure] Q.cell.indicator (fun _ => c) :=
      MeasureTheory.indicatorConstLp_coeFn (μ := G.toWeakGridSpace.measure)
        (p := p) (hs := G.grid.grid.measurable Q.level Q.cell Q.mem)
        (hμs := GoodGridCell.measure_ne_top Q) (c := c)
    refine hxcoe.trans (Filter.Eventually.of_forall ?_)
    intro z
    by_cases hz : z ∈ Q.cell
    · simp [canonicalSouzaAtom, c, hz]
    · simp [canonicalSouzaAtom, c, hz]

/--
A `selfs` bound controls the `L^p` norm of the product with any normalized
Souza atom.

This is the formal version of the estimate obtained in the paper by testing
`g` on one atom and then applying the Besov-to-`L^p` embedding with `t = p`.
The remaining step toward the full `L^\infty` theorem is the martingale/Levy
argument turning the resulting uniform cell-average bounds into an essential
supremum bound.
-/
theorem souzaPointwiseSelfsBound_atomicUnit_product_eLpNorm_le
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C)
    (x : WeakGridSpace.BesovishSpace
      (souzaAtomFamily G s p hs hp hp_top) q)
    (hx : WeakGridSpace.AtomicUnit
      (A := souzaAtomFamily G s p hs hp hp_top) q x) :
    ∃ y : WeakGridSpace.BesovishSpace
      (souzaAtomFamily G s p hs hp hp_top) q,
      WeakGridSpace.RepresentsPointwiseProduct
        (G := G.toWeakGridSpace) (p := p) m
        (x : Lp ℂ p G.toWeakGridSpace.measure)
        (y : Lp ℂ p G.toWeakGridSpace.measure) ∧
      (eLpNorm ((y : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
        p G.toWeakGridSpace.measure).toReal ≤
        souzaBesovLpEmbeddingConstant G s p q * C := by
  classical
  let A := souzaAtomFamily G s p hs hp hp_top
  rcases hC.2 x hx with ⟨y, hprod, hy_cost⟩
  refine ⟨y, hprod, ?_⟩
  have hs_nonneg : 0 ≤ s - 1 / p.toReal + 1 / p.toReal := by
    linarith [hs.le]
  have ht_le_pu : p ≤ p * (∞ : ℝ≥0∞) := by
    calc
      p = p * 1 := by rw [mul_one]
      _ ≤ p * (∞ : ℝ≥0∞) := by
        exact mul_le_mul_right le_top p
  have hAfinite :
      WeakGridSpace.BesovishSpace.HasFiniteCostRepresentations (A := A) q :=
    WeakGridSpace.BesovishSpace.hasFiniteCostRepresentations (A := A) q
  have hLp :
      (eLpNorm ((y : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
        p G.toWeakGridSpace.measure).toReal ≤
        souzaBesovLpEmbeddingConstant G s p q *
          WeakGridSpace.BesovishSpace.Norm_Costpq A q y := by
    simpa [souzaBesovLpEmbeddingConstant, A] using
      WeakGridSpace.BesovishSpace.lp_norm_le_const_mul_Norm_Costpq
        (G := G.toWeakGridSpace) (s := s) (p := p) (u := ∞) (q := q)
        (A := A) (t := p)
        hp_top hp_top le_rfl ht_le_pu hs_nonneg
        (souza_assumptionG2 G s p q hs hp hp_top).1 hAfinite y
  have hconst_nonneg : 0 ≤ souzaBesovLpEmbeddingConstant G s p q := by
    dsimp [souzaBesovLpEmbeddingConstant]
    exact mul_nonneg
      (by positivity)
      (WeakGridSpace.LpGridRepresentation.cCoefficient_nonneg p q
        (fun k =>
          (WeakGridSpace.LpGridRepresentation.levelMeasureWeight
            G.toWeakGridSpace s p p k) ^ p.toReal)
        (fun k => Real.rpow_nonneg
          (WeakGridSpace.LpGridRepresentation.levelMeasureWeight_nonneg
            G.toWeakGridSpace s p p k) _))
  calc
    (eLpNorm ((y : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
        p G.toWeakGridSpace.measure).toReal
        ≤ souzaBesovLpEmbeddingConstant G s p q *
            WeakGridSpace.BesovishSpace.Norm_Costpq A q y := hLp
    _ ≤ souzaBesovLpEmbeddingConstant G s p q * C :=
      mul_le_mul_of_nonneg_left hy_cost hconst_nonneg

/--
A `selfs` bound controls the concrete product with the canonical Souza atom on
each good-grid cell.
-/
theorem souzaPointwiseSelfsBound_canonicalAtom_product_eLpNorm_le
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C)
    (Q : GoodGridCell G) :
    ∃ y : WeakGridSpace.BesovishSpace
      (souzaAtomFamily G s p hs hp hp_top) q,
      WeakGridSpace.RepresentsFunction
        (G := G.toWeakGridSpace) (p := p)
        (fun z => m z * canonicalSouzaAtom G s p Q z)
        (y : Lp ℂ p G.toWeakGridSpace.measure) ∧
      (eLpNorm ((y : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
        p G.toWeakGridSpace.measure).toReal ≤
        souzaBesovLpEmbeddingConstant G s p q * C := by
  classical
  rcases exists_canonicalSouzaAtomicUnit G s p q hs hp hp_top Q with
    ⟨x, hx_unit, hx_rep⟩
  rcases souzaPointwiseSelfsBound_atomicUnit_product_eLpNorm_le
      G s p q hs hp hp_top hC x hx_unit with
    ⟨y, hprod, hy_bound⟩
  refine ⟨y, ?_, hy_bound⟩
  filter_upwards [hprod, hx_rep] with z hprod_z hx_z
  calc
    ((y : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ) z
        = m z * ((x : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ) z := hprod_z
    _ = m z * canonicalSouzaAtom G s p Q z := by rw [hx_z]

/--
A cost bound in the Souza Besov space induced on a cell controls the local
`L^p` norm on that induced grid.
-/
theorem inducedSouzaBesov_eLpNorm_le
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (y : WeakGridSpace.BesovishSpace
      (WeakGridSpace.inducedAtomFamily G.toWeakGridSpace Q.toLevelCell
        (souzaAtomFamily G s p hs hp hp_top)) q) :
    (eLpNorm
        ((y : Lp ℂ p
          (WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell).measure) :
          α → ℂ)
        p
        (WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell).measure).toReal ≤
      inducedSouzaBesovLpEmbeddingConstant G Q s p q *
        WeakGridSpace.BesovishSpace.Norm_Costpq
          (WeakGridSpace.inducedAtomFamily G.toWeakGridSpace Q.toLevelCell
            (souzaAtomFamily G s p hs hp hp_top)) q y := by
  classical
  let Wi := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell
  let Ai := WeakGridSpace.inducedAtomFamily G.toWeakGridSpace Q.toLevelCell
    (souzaAtomFamily G s p hs hp hp_top)
  have hs_nonneg : 0 ≤ s - 1 / p.toReal + 1 / p.toReal := by
    linarith [hs.le]
  have ht_le_pu : p ≤ p * (∞ : ℝ≥0∞) := by
    calc
      p = p * 1 := by rw [mul_one]
      _ ≤ p * (∞ : ℝ≥0∞) := by
        exact mul_le_mul_right le_top p
  have hAfinite :
      WeakGridSpace.BesovishSpace.HasFiniteCostRepresentations (A := Ai) q :=
    WeakGridSpace.BesovishSpace.hasFiniteCostRepresentations (A := Ai) q
  have hG2 :
      WeakGridSpace.AssumptionG2 Wi s p ∞ q :=
    induced_souza_assumptionG2 G s p q hs hp hp_top Q
  simpa [inducedSouzaBesovLpEmbeddingConstant, Wi, Ai] using
    WeakGridSpace.BesovishSpace.lp_norm_le_const_mul_Norm_Costpq
      (G := Wi) (s := s) (p := p) (u := ∞) (q := q)
      (A := Ai) (t := p)
      hp_top hp_top le_rfl ht_le_pu hs_nonneg hG2.1 hAfinite y

/--
Local estimate for the product with a canonical Souza atom.

The uniform cell-indicator multiplier theorem supplies the localization to the
grid induced by `Q`, so a `selfs` bound controls the induced `L^p` norm of
`m * a_Q` with the correct cell factor `μ(Q)^s`.
-/
theorem souzaPointwiseSelfsBound_cellCanonicalAtom_eLpNorm_le
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    ∃ y : WeakGridSpace.BesovishSpace
        (WeakGridSpace.inducedAtomFamily G.toWeakGridSpace Q.toLevelCell
          (souzaAtomFamily G s p hs hp hp_top)) q,
      WeakGridSpace.RepresentsFunction
        (G := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell)
        (p := p)
        (fun z => Q.cell.indicator (fun _ => (1 : ℂ)) z *
          (m z * canonicalSouzaAtom G s p Q z))
        (y : Lp ℂ p
          (WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell).measure) ∧
      (eLpNorm
          ((y : Lp ℂ p
            (WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell).measure) :
            α → ℂ)
          p
          (WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell).measure).toReal ≤
        (G.grid.μ Q.cell).toReal ^ s *
          souzaBesovLpLocalEmbeddingConstant G s p q *
            (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C := by
  classical
  let A := souzaAtomFamily G s p hs hp hp_top
  let Wi := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell
  let Ai := WeakGridSpace.inducedAtomFamily G.toWeakGridSpace Q.toLevelCell A
  let D : ℝ := 2 * souzaAmbientRestrictionMultiplierConstant G s p + 1
  have hD : 0 ≤ D := by
    have hBound :=
      souzaCellIndicatorPointwiseMultiplierBound_uniform
        G s p q hs hp hp_top hs_lt_inv Q
    simpa [D] using hBound.1
  rcases exists_canonicalSouzaAtomicUnit G s p q hs hp hp_top Q with
    ⟨x, hx_unit, hx_rep⟩
  rcases hC.2 x hx_unit with ⟨z, hz_prod, hz_norm⟩
  have hcellProduct :
      ∃ y : WeakGridSpace.BesovishSpace Ai q,
        WeakGridSpace.RepresentsPointwiseProduct
          (G := Wi) (p := p) (Q.cell.indicator fun _ => (1 : ℂ))
          (z : Lp ℂ p G.toWeakGridSpace.measure)
          (y : Lp ℂ p Wi.measure) ∧
        WeakGridSpace.BesovishSpace.Norm_Costpq Ai q y ≤
          D * WeakGridSpace.BesovishSpace.Norm_Costpq A q z := by
    simpa [A, Ai, Wi, D] using
      souzaCellIndicatorRestrictsToInduced
        G s p q hs hp hp_top hs_lt_inv Q z
  rcases hcellProduct with ⟨y, hy_prod, hy_norm⟩
  refine ⟨y, ?_, ?_⟩
  · have hz_prod_i :
        ((z : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
          =ᵐ[Wi.measure]
            fun t => m t * ((x : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ) t := by
      simpa [Wi, WeakGridSpace.inducedWeakGridSpace, WeakGridSpace.inducedWeakGrid,
        GoodGridSpace.toWeakGridSpace, GoodGridSpace.toWeakGrid,
        WeakGridSpace.WeakGridSpace.measure] using hz_prod
    have hx_rep_i :
        ((x : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ)
          =ᵐ[Wi.measure] canonicalSouzaAtom G s p Q := by
      simpa [Wi, WeakGridSpace.inducedWeakGridSpace, WeakGridSpace.inducedWeakGrid,
        GoodGridSpace.toWeakGridSpace, GoodGridSpace.toWeakGrid,
        WeakGridSpace.WeakGridSpace.measure] using hx_rep
    filter_upwards [hy_prod, hz_prod_i, hx_rep_i] with t hy_t hz_t hx_t
    calc
      ((y : Lp ℂ p Wi.measure) : α → ℂ) t
          = Q.cell.indicator (fun _ => (1 : ℂ)) t *
              ((z : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ) t := hy_t
      _ = Q.cell.indicator (fun _ => (1 : ℂ)) t *
            (m t * ((x : Lp ℂ p G.toWeakGridSpace.measure) : α → ℂ) t) := by rw [hz_t]
      _ = Q.cell.indicator (fun _ => (1 : ℂ)) t *
            (m t * canonicalSouzaAtom G s p Q t) := by rw [hx_t]
  · have hind_nonneg : 0 ≤ inducedSouzaBesovLpEmbeddingConstant G Q s p q := by
      dsimp [inducedSouzaBesovLpEmbeddingConstant]
      exact mul_nonneg
        (by positivity)
        (WeakGridSpace.LpGridRepresentation.cCoefficient_nonneg p q
          (fun k =>
            (WeakGridSpace.LpGridRepresentation.levelMeasureWeight
              Wi s p p k) ^ p.toReal)
          (fun k => Real.rpow_nonneg
            (WeakGridSpace.LpGridRepresentation.levelMeasureWeight_nonneg
              Wi s p p k) _))
    have hAfinite :
        WeakGridSpace.BesovishSpace.HasFiniteCostRepresentations (A := A) q :=
      WeakGridSpace.BesovishSpace.hasFiniteCostRepresentations (A := A) q
    have hz_norm_nonneg :
        0 ≤ WeakGridSpace.BesovishSpace.Norm_Costpq A q z :=
      WeakGridSpace.BesovishSpace.Norm_Costpq_nonneg
        (A := A) (q := q) hAfinite z
    have hy_norm_le : WeakGridSpace.BesovishSpace.Norm_Costpq Ai q y ≤ D * C := by
      calc
        WeakGridSpace.BesovishSpace.Norm_Costpq Ai q y
            ≤ D * WeakGridSpace.BesovishSpace.Norm_Costpq A q z := by
              simpa [A, Ai] using hy_norm
        _ ≤ D * C := mul_le_mul_of_nonneg_left hz_norm hD
    have hDC_nonneg : 0 ≤ D * C := mul_nonneg hD hC.1
    have hscale :
        inducedSouzaBesovLpEmbeddingConstant G Q s p q ≤
          (G.grid.μ Q.cell).toReal ^ s *
            souzaBesovLpLocalEmbeddingConstant G s p q :=
      inducedSouzaBesovLpEmbeddingConstant_le_cellScale G Q s p q hs hp_top
    calc
      (eLpNorm
          ((y : Lp ℂ p Wi.measure) : α → ℂ)
          p Wi.measure).toReal
          ≤ inducedSouzaBesovLpEmbeddingConstant G Q s p q *
              WeakGridSpace.BesovishSpace.Norm_Costpq Ai q y := by
            simpa [Wi, Ai, A] using
              inducedSouzaBesov_eLpNorm_le G Q s p q hs hp hp_top y
      _ ≤ inducedSouzaBesovLpEmbeddingConstant G Q s p q * (D * C) :=
            mul_le_mul_of_nonneg_left hy_norm_le hind_nonneg
      _ ≤ ((G.grid.μ Q.cell).toReal ^ s *
            souzaBesovLpLocalEmbeddingConstant G s p q) * (D * C) :=
            mul_le_mul_of_nonneg_right hscale hDC_nonneg
      _ = (G.grid.μ Q.cell).toReal ^ s *
          souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
            ring

/--
The local estimate also gives local `L^p` membership of the multiplier.

This records the measurability information hidden in the representative on the
induced grid: after dividing by the nonzero canonical Souza atom amplitude,
`1_Q m` is an `L^p` function on the ambient grid.
-/
theorem souzaPointwiseSelfsBound_cellIndicator_memLp
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    MemLp (Q.cell.indicator m) p G.grid.μ := by
  classical
  let Wi := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell
  let μQ : ℝ := (G.grid.μ Q.cell).toReal
  let a : ℝ := μQ ^ (s - (p.toReal)⁻¹)
  let prod : α → ℂ := fun z =>
    Q.cell.indicator (fun _ => (1 : ℂ)) z *
      (m z * canonicalSouzaAtom G s p Q z)
  have hμQ_pos : 0 < μQ := by
    exact ENNReal.toReal_pos (GoodGridCell.measure_pos Q).ne' (GoodGridCell.measure_ne_top Q)
  have ha_pos : 0 < a := by
    exact Real.rpow_pos_of_pos hμQ_pos _
  rcases
    souzaPointwiseSelfsBound_cellCanonicalAtom_eLpNorm_le
      G Q s p q hs hp hp_top hs_lt_inv hC with
    ⟨y, hy_rep, _hy_bound⟩
  have hprod_mem : MemLp prod p G.grid.μ := by
    have hy_mem :
        MemLp
          ((y : Lp ℂ p Wi.measure) : α → ℂ)
          p Wi.measure :=
      Lp.memLp (y : Lp ℂ p Wi.measure)
    have hy_mem_ambient :
        MemLp
          ((y : Lp ℂ p Wi.measure) : α → ℂ)
          p G.grid.μ := by
      simpa [Wi, WeakGridSpace.inducedWeakGridSpace, WeakGridSpace.inducedWeakGrid,
        GoodGridSpace.toWeakGridSpace, GoodGridSpace.toWeakGrid,
        WeakGridSpace.WeakGridSpace.measure] using hy_mem
    exact hy_mem_ambient.ae_eq (by
      simpa [prod, Wi, WeakGridSpace.inducedWeakGridSpace, WeakGridSpace.inducedWeakGrid,
        GoodGridSpace.toWeakGridSpace, GoodGridSpace.toWeakGrid,
        WeakGridSpace.WeakGridSpace.measure] using hy_rep)
  have hindicator_eq : Q.cell.indicator m = (a : ℂ)⁻¹ • prod := by
    have haC_ne : (a : ℂ) ≠ 0 := by
      exact_mod_cast ha_pos.ne'
    funext z
    by_cases hz : z ∈ Q.cell
    · simp [prod, canonicalSouzaAtom, hz]
      change m z = (a : ℂ)⁻¹ * (m z * (a : ℂ))
      calc
        m z = (1 : ℂ) * m z := by rw [one_mul]
        _ = ((a : ℂ)⁻¹ * (a : ℂ)) * m z := by rw [inv_mul_cancel₀ haC_ne]
        _ = (a : ℂ)⁻¹ * (m z * (a : ℂ)) := by ring
    · simp [prod, canonicalSouzaAtom, hz]
  simpa [hindicator_eq] using hprod_mem.const_smul ((a : ℂ)⁻¹)

/--
A quantitative local `L^p` estimate for the multiplier itself on one cell.

The previous lemma estimates the product with the canonical Souza atom
`a_Q = μ(Q)^(s - 1 / p) 1_Q`.  Since this amplitude is strictly positive, we
can divide it out and recover the expected scale
`μ(Q)^(1 / p)` for the local `L^p` norm of `1_Q m`.
-/
theorem souzaPointwiseSelfsBound_cellIndicator_eLpNorm_le
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    (eLpNorm (Q.cell.indicator m) p G.grid.μ).toReal ≤
      (G.grid.μ Q.cell).toReal ^ (p.toReal)⁻¹ *
        souzaBesovLpLocalEmbeddingConstant G s p q *
          (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C := by
  classical
  let Wi := WeakGridSpace.inducedWeakGridSpace G.toWeakGridSpace Q.toLevelCell
  let μQ : ℝ := (G.grid.μ Q.cell).toReal
  let a : ℝ := μQ ^ (s - (p.toReal)⁻¹)
  let prod : α → ℂ := fun z =>
    Q.cell.indicator (fun _ => (1 : ℂ)) z *
      (m z * canonicalSouzaAtom G s p Q z)
  let D : ℝ := 2 * souzaAmbientRestrictionMultiplierConstant G s p + 1
  have hμQ_pos : 0 < μQ := by
    exact ENNReal.toReal_pos (GoodGridCell.measure_pos Q).ne' (GoodGridCell.measure_ne_top Q)
  have ha_pos : 0 < a := by
    exact Real.rpow_pos_of_pos hμQ_pos _
  rcases
    souzaPointwiseSelfsBound_cellCanonicalAtom_eLpNorm_le
      G Q s p q hs hp hp_top hs_lt_inv hC with
    ⟨y, hy_rep, hy_bound⟩
  have hprod_bound :
      (eLpNorm prod p G.grid.μ).toReal ≤
        μQ ^ s * souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
    have hnorm_eq :
        eLpNorm prod p G.grid.μ =
          eLpNorm
            ((y : Lp ℂ p Wi.measure) : α → ℂ)
            p Wi.measure := by
      simpa [prod, Wi, WeakGridSpace.inducedWeakGridSpace, WeakGridSpace.inducedWeakGrid,
        GoodGridSpace.toWeakGridSpace, GoodGridSpace.toWeakGrid,
        WeakGridSpace.WeakGridSpace.measure] using
        (MeasureTheory.eLpNorm_congr_ae hy_rep.symm)
    rw [hnorm_eq]
    simpa [μQ, Wi] using hy_bound
  have hindicator_eq : Q.cell.indicator m = (a : ℂ)⁻¹ • prod := by
    have haC_ne : (a : ℂ) ≠ 0 := by
      exact_mod_cast ha_pos.ne'
    funext z
    by_cases hz : z ∈ Q.cell
    · simp [prod, canonicalSouzaAtom, hz]
      change m z = (a : ℂ)⁻¹ * (m z * (a : ℂ))
      calc
        m z = (1 : ℂ) * m z := by rw [one_mul]
        _ = ((a : ℂ)⁻¹ * (a : ℂ)) * m z := by rw [inv_mul_cancel₀ haC_ne]
        _ = (a : ℂ)⁻¹ * (m z * (a : ℂ)) := by ring
    · simp [prod, canonicalSouzaAtom, hz]
  have hinv_norm :
      ‖((a : ℂ)⁻¹)‖ = a⁻¹ := by
    rw [norm_inv, Complex.norm_real, Real.norm_of_nonneg ha_pos.le]
  have hscale :
      a⁻¹ * (μQ ^ s * souzaBesovLpLocalEmbeddingConstant G s p q * D * C) =
        μQ ^ (p.toReal)⁻¹ *
          souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
    have hpow :
        a⁻¹ * μQ ^ s = μQ ^ (p.toReal)⁻¹ := by
      calc
        a⁻¹ * μQ ^ s
            = μQ ^ (-(s - (p.toReal)⁻¹)) * μQ ^ s := by
                rw [show a⁻¹ = μQ ^ (-(s - (p.toReal)⁻¹)) by
                  change (μQ ^ (s - (p.toReal)⁻¹))⁻¹ =
                    μQ ^ (-(s - (p.toReal)⁻¹))
                  rw [Real.rpow_neg hμQ_pos.le]]
        _ = μQ ^ (-(s - (p.toReal)⁻¹) + s) := by
                rw [← Real.rpow_add hμQ_pos]
        _ = μQ ^ (p.toReal)⁻¹ := by ring_nf
    calc
      a⁻¹ * (μQ ^ s * souzaBesovLpLocalEmbeddingConstant G s p q * D * C)
          = (a⁻¹ * μQ ^ s) *
              souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by ring
      _ = μQ ^ (p.toReal)⁻¹ *
          souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by rw [hpow]
  calc
    (eLpNorm (Q.cell.indicator m) p G.grid.μ).toReal
        = (eLpNorm ((a : ℂ)⁻¹ • prod) p G.grid.μ).toReal := by
            rw [hindicator_eq]
    _ = (‖((a : ℂ)⁻¹)‖ₑ * eLpNorm prod p G.grid.μ).toReal := by
            rw [MeasureTheory.eLpNorm_const_smul]
    _ = a⁻¹ * (eLpNorm prod p G.grid.μ).toReal := by
            have hinv_enorm : ‖((a : ℂ)⁻¹)‖ₑ = ENNReal.ofReal a⁻¹ := by
              rw [← ofReal_norm_eq_enorm, hinv_norm]
            rw [ENNReal.toReal_mul]
            rw [hinv_enorm, ENNReal.toReal_ofReal (inv_nonneg.mpr ha_pos.le)]
    _ ≤ a⁻¹ *
        (μQ ^ s * souzaBesovLpLocalEmbeddingConstant G s p q * D * C) := by
            exact mul_le_mul_of_nonneg_left hprod_bound (inv_nonneg.mpr ha_pos.le)
    _ = μQ ^ (p.toReal)⁻¹ *
        souzaBesovLpLocalEmbeddingConstant G s p q * D * C := hscale

/--
Uniform `L¹` control on one cell, obtained by combining the local `L^p`
estimate with Hölder on that cell.

After dividing by `μ(Q)`, this is the formal cell-average bound for `|m|`.
-/
theorem souzaPointwiseSelfsBound_cellIndicator_eLpNorm_one_le
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    (eLpNorm (Q.cell.indicator m) 1 G.grid.μ).toReal ≤
      (G.grid.μ Q.cell).toReal *
        souzaBesovLpLocalEmbeddingConstant G s p q *
          (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C := by
  classical
  let μQ : ℝ := (G.grid.μ Q.cell).toReal
  let D : ℝ := 2 * souzaAmbientRestrictionMultiplierConstant G s p + 1
  have hμQ_pos : 0 < μQ := by
    exact ENNReal.toReal_pos (GoodGridCell.measure_pos Q).ne' (GoodGridCell.measure_ne_top Q)
  have hmem :
      MemLp (Q.cell.indicator m) p G.grid.μ :=
    souzaPointwiseSelfsBound_cellIndicator_memLp
      G Q s p q hs hp hp_top hs_lt_inv hC
  have hholder :=
    eLpNorm_one_cellIndicator_le_eLpNorm_mul_measure_rpow
      G Q p hp hmem
  have hholder_real :
      (eLpNorm (Q.cell.indicator m) 1 G.grid.μ).toReal ≤
        (eLpNorm (Q.cell.indicator m) p G.grid.μ).toReal *
          μQ ^ (1 - 1 / p.toReal) := by
    have hp_toReal_pos : 0 < p.toReal :=
      ENNReal.toReal_pos (zero_lt_one.trans_le hp).ne' hp_top
    have hp_toReal_ge_one : 1 ≤ p.toReal := by
      simpa using ENNReal.toReal_mono hp_top hp
    have hexp_nonneg : 0 ≤ 1 - 1 / p.toReal := by
      have hinv_le_one : 1 / p.toReal ≤ 1 := by
        rw [div_le_iff₀ hp_toReal_pos]
        simpa using hp_toReal_ge_one
      linarith
    have hright_ne_top :
        eLpNorm (Q.cell.indicator m) p G.grid.μ *
            G.grid.μ Q.cell ^ (1 - 1 / p.toReal) ≠ ∞ := by
      exact ENNReal.mul_ne_top hmem.eLpNorm_lt_top.ne
        (ENNReal.rpow_lt_top_of_nonneg hexp_nonneg (GoodGridCell.measure_ne_top Q)).ne
    have hreal := ENNReal.toReal_mono hright_ne_top hholder
    rw [ENNReal.toReal_mul, ← ENNReal.toReal_rpow] at hreal
    simpa [μQ] using hreal
  have hLp :
      (eLpNorm (Q.cell.indicator m) p G.grid.μ).toReal ≤
        μQ ^ (p.toReal)⁻¹ *
          souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
    simpa [μQ] using
      souzaPointwiseSelfsBound_cellIndicator_eLpNorm_le
        G Q s p q hs hp hp_top hs_lt_inv hC
  have hpow :
      μQ ^ (p.toReal)⁻¹ * μQ ^ (1 - 1 / p.toReal) = μQ := by
    calc
      μQ ^ (p.toReal)⁻¹ * μQ ^ (1 - 1 / p.toReal)
          = μQ ^ ((p.toReal)⁻¹ + (1 - 1 / p.toReal)) := by
            rw [← Real.rpow_add hμQ_pos]
      _ = μQ := by
            ring_nf
            rw [Real.rpow_one]
  calc
    (eLpNorm (Q.cell.indicator m) 1 G.grid.μ).toReal
        ≤ (eLpNorm (Q.cell.indicator m) p G.grid.μ).toReal *
            μQ ^ (1 - 1 / p.toReal) := hholder_real
    _ ≤ (μQ ^ (p.toReal)⁻¹ *
          souzaBesovLpLocalEmbeddingConstant G s p q * D * C) *
            μQ ^ (1 - 1 / p.toReal) := by
          exact mul_le_mul_of_nonneg_right hLp
            (Real.rpow_nonneg hμQ_pos.le _)
    _ = μQ * souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
          calc
            (μQ ^ (p.toReal)⁻¹ *
                souzaBesovLpLocalEmbeddingConstant G s p q * D * C) *
                μQ ^ (1 - 1 / p.toReal)
                = (μQ ^ (p.toReal)⁻¹ * μQ ^ (1 - 1 / p.toReal)) *
                    souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
                  ring
            _ = μQ * souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
                  rw [hpow]
    _ = (G.grid.μ Q.cell).toReal *
        souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
          rfl

/--
The previous `L¹` estimate written as an average estimate over the cell.

This is the form used by the martingale argument: the integral of `‖m‖` over
each grid cell is controlled by the cell measure times the same global
constant.
-/
theorem souzaPointwiseSelfsBound_cellIntegral_norm_le
    (G : GoodGridSpace (α := α)) (Q : GoodGridCell G)
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    ∫ x in Q.cell, ‖m x‖ ∂G.grid.μ ≤
      (G.grid.μ Q.cell).toReal *
        souzaBesovLpLocalEmbeddingConstant G s p q *
          (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C := by
  classical
  let D : ℝ := 2 * souzaAmbientRestrictionMultiplierConstant G s p + 1
  have hQm : MeasurableSet Q.cell := G.grid.grid.measurable Q.level Q.cell Q.mem
  have hmem :
      MemLp (Q.cell.indicator m) p G.grid.μ :=
    souzaPointwiseSelfsBound_cellIndicator_memLp
      G Q s p q hs hp hp_top hs_lt_inv hC
  have hL1 :=
    souzaPointwiseSelfsBound_cellIndicator_eLpNorm_one_le
      G Q s p q hs hp hp_top hs_lt_inv hC
  have hnorm_indicator :
      (fun x => ‖Q.cell.indicator m x‖) = Q.cell.indicator (fun x => ‖m x‖) := by
    funext x
    by_cases hx : x ∈ Q.cell
    · simp [Set.indicator_of_mem hx]
    · simp [Set.indicator_of_notMem hx]
  have hsetIntegral :
      ∫ x in Q.cell, ‖m x‖ ∂G.grid.μ =
        ∫ x, ‖Q.cell.indicator m x‖ ∂G.grid.μ := by
    rw [hnorm_indicator, integral_indicator hQm]
  have heLpNorm_integral :
      (eLpNorm (Q.cell.indicator m) 1 G.grid.μ).toReal =
        ∫ x, ‖Q.cell.indicator m x‖ ∂G.grid.μ := by
    rw [eLpNorm_one_eq_lintegral_enorm]
    exact (integral_norm_eq_lintegral_enorm hmem.aestronglyMeasurable).symm
  calc
    ∫ x in Q.cell, ‖m x‖ ∂G.grid.μ
        = (eLpNorm (Q.cell.indicator m) 1 G.grid.μ).toReal := by
            rw [hsetIntegral, heLpNorm_integral]
    _ ≤ (G.grid.μ Q.cell).toReal *
        souzaBesovLpLocalEmbeddingConstant G s p q * D * C := hL1

/--
The root-cell estimate gives the integrability needed to apply the martingale
convergence theorem to the real-valued function `‖m‖`.
-/
theorem souzaPointwiseSelfsBound_norm_integrable
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    Integrable (fun x => ‖m x‖) G.grid.μ := by
  classical
  let Q := rootGoodGridCell G
  haveI : IsFiniteMeasure G.grid.μ := G.grid.isFinite
  have hmem_indicator :
      MemLp (Q.cell.indicator m) p G.grid.μ :=
    souzaPointwiseSelfsBound_cellIndicator_memLp
      G Q s p q hs hp hp_top hs_lt_inv hC
  have hmem : MemLp m p G.grid.μ := by
    simpa [Q, rootGoodGridCell] using hmem_indicator
  have hmem_one : MemLp m 1 G.grid.μ :=
    hmem.mono_exponent hp
  exact (memLp_one_iff_integrable.1 hmem_one).norm

/--
The cell-average process for `‖m‖` is uniformly bounded at every finite grid
level.  The needed cell localization is supplied by the uniform cell-indicator
multiplier theorem.
-/
theorem souzaPointwiseSelfsBound_goodGridLevelAverage_norm_le
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C)
    (n : ℕ) :
    ∀ x,
      goodGridLevelAverage G (fun z => ‖m z‖) n x ≤
        souzaBesovLpLocalEmbeddingConstant G s p q *
          (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C := by
  classical
  let D : ℝ := 2 * souzaAmbientRestrictionMultiplierConstant G s p + 1
  refine goodGridLevelAverage_le_of_cellIntegral_le G (fun z => ‖m z‖) n ?_
  intro cell hcell
  let Q : GoodGridCell G := { level := n, cell := cell, mem := hcell }
  calc
    ∫ y in cell, ‖m y‖ ∂G.grid.μ
        ≤ (G.grid.μ cell).toReal *
            souzaBesovLpLocalEmbeddingConstant G s p q * D * C := by
          simpa [Q] using
            souzaPointwiseSelfsBound_cellIntegral_norm_le
              G Q s p q hs hp hp_top hs_lt_inv hC
    _ = (G.grid.μ cell).toReal *
        (souzaBesovLpLocalEmbeddingConstant G s p q * D * C) := by
          ring

/--
The martingale step specialized to Souza `selfs` bounds.

The finite-level average of `‖m‖` is the conditional expectation on the
corresponding finite grid sigma-algebra, so Levy's theorem turns the uniform
cell-average bounds into the desired almost-everywhere bound.
-/
theorem souzaPointwiseSelfsBound_norm_ae_le
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ} {C : ℝ}
    (hC : WeakGridSpace.PointwiseSelfsBound
      (A := souzaAtomFamily G s p hs hp hp_top) q m C) :
    ∀ᵐ x ∂G.grid.μ,
      ‖m x‖ ≤
        souzaBesovLpLocalEmbeddingConstant G s p q *
          (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C := by
  classical
  let D : ℝ := 2 * souzaAmbientRestrictionMultiplierConstant G s p + 1
  have hnorm_int :
      Integrable (fun z => ‖m z‖) G.grid.μ :=
    souzaPointwiseSelfsBound_norm_integrable
      G s p q hs hp hp_top hs_lt_inv hC
  have havg_le :
      ∀ n x,
        goodGridLevelAverage G (fun z => ‖m z‖) n x ≤
          souzaBesovLpLocalEmbeddingConstant G s p q * D * C :=
    souzaPointwiseSelfsBound_goodGridLevelAverage_norm_le
      G s p q hs hp hp_top hs_lt_inv hC
  exact ae_le_of_goodGridLevelAverage_le G hnorm_int havg_le

/--
Every Souza `selfs` function is bounded almost everywhere.

This is the qualitative form of `souzaPointwiseSelfsBound_norm_ae_le`: the
bound may depend on the chosen `selfs` constant.
-/
theorem souzaPointwiseSelfsClass_norm_ae_bounded
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ}
    (hm : SouzaPointwiseSelfsClass G s p q hs hp hp_top m) :
    ∃ M : ℝ, ∀ᵐ x ∂G.grid.μ, ‖m x‖ ≤ M := by
  classical
  rcases hm with ⟨C, hC⟩
  refine ⟨souzaBesovLpLocalEmbeddingConstant G s p q *
    (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C, ?_⟩
  exact souzaPointwiseSelfsBound_norm_ae_le
    G s p q hs hp hp_top hs_lt_inv hC

/--
Every Souza pointwise multiplier is bounded almost everywhere.

The statement is proved for every `q >= 1`, including `q = ∞`; in particular
it covers the finite-`q` range.
-/
theorem souzaPointwiseMultiplier_norm_ae_bounded
    (G : GoodGridSpace (α := α))
    (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (hs_lt_inv : s < (p.toReal)⁻¹)
    {m : α → ℂ}
    (hm : SouzaPointwiseMultiplier G s p q hs hp hp_top m) :
    ∃ M : ℝ, ∀ᵐ x ∂G.grid.μ, ‖m x‖ ≤ M := by
  classical
  rcases hm with ⟨C, hC⟩
  refine ⟨souzaBesovLpLocalEmbeddingConstant G s p q *
    (2 * souzaAmbientRestrictionMultiplierConstant G s p + 1) * C, ?_⟩
  exact souzaPointwiseSelfsBound_norm_ae_le
    G s p q hs hp hp_top hs_lt_inv hC.selfsBound

end

end GoodGridSpace
