import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.HaarRepresentationNorm
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.HaarParametrizedRepresentation
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.ComparingHaarRepresentationsl
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.standardRepresentation
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.standardNormleqHaarRepresenstionNorm
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.FiniteStandardNormimpliesBesov
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.FiniteHaarNormimpliesLp
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.MeanOscillationNorm
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.OscillationNormleqBesovNorm
import BesovSpacesGoodGrid.GoodGrid.AlternativeRepresentationsAndNorms.HaarNormleqOscillationNorm

/-!
# Alternative representations and comparison norms

This module gathers the good-grid files about Haar and standard
representations, mean oscillation, and the comparison estimates between the
corresponding Besov-style norms.
-/
