import BesovSpacesGoodGrid.GoodGrid.Definition
import Mathlib.MeasureTheory.Function.SimpleFunc

/-!
Test functions and distributions associated to a good grid.
-/

namespace GoodGridSpace

variable {α : Type*} [MeasurableSpace α]

/--
A partition-cell indicator as a real-valued simple function.
-/
noncomputable def atomIndicator
    (G : GoodGridSpace (α := α)) (m : ℕ) (A : Set α)
    (hA : A ∈ G.grid.grid.partitions m) : MeasureTheory.SimpleFunc α ℝ :=
  MeasureTheory.SimpleFunc.piecewise A (G.grid.grid.measurable m A hA)
    (MeasureTheory.SimpleFunc.const α (1 : ℝ))
    (MeasureTheory.SimpleFunc.const α (0 : ℝ))

/--
The set of all indicator simple functions attached to partition atoms of the
good grid, at all levels.
-/
def atomIndicators (G : GoodGridSpace (α := α)) : Set (MeasureTheory.SimpleFunc α ℝ) :=
  { f |
    ∃ (m : ℕ) (A : Set α) (hA : A ∈ G.grid.grid.partitions m),
      f = atomIndicator G m A hA }

/--
The test-function space generated by all partition-atom indicators.
-/
def TestFunctions (G : GoodGridSpace (α := α)) : Submodule ℝ (MeasureTheory.SimpleFunc α ℝ) :=
  Submodule.span ℝ (atomIndicators G)

/--
Distributions as real-linear functionals on the test-function space.
-/
def Distributions (G : GoodGridSpace (α := α)) : Type _ :=
  Module.Dual ℝ (TestFunctions G)

end GoodGridSpace
