import BesovSpacesGoodGrid.GoodGrid.BesovSpace

/-!
# Pointwise multipliers for Besov-ish spaces

This file starts the formalization of the multiplier section of the paper.
The main point here is definitional: we package pointwise multiplication by a
measurable function as a bounded operation on an atomic Besov-ish space, and we
also package the Triebel-style `selfs` condition obtained by testing the
multiplier only on unit atoms.

The heavier multiplier theorems from the paper, such as
`M(B^s_{1,1}) = B^s_{1,1,selfs}` and the restriction lemma for indicators of
grid cells, should build on these definitions.
-/

open scoped ENNReal BigOperators Topology
open MeasureTheory

namespace WeakGridSpace

universe u

variable {α : Type u} [MeasurableSpace α]

noncomputable section

variable {G : WeakGridSpace (α := α)} {s : ℝ} {p u q : ℝ≥0∞}

/--
An `Lp` vector represents a concrete function if its chosen representative
agrees with that function almost everywhere.

This is the bridge between the paper's pointwise formulas and the quotient
model of `L^p` used by Mathlib.
-/
def RepresentsFunction (f : α → ℂ) (x : Lp ℂ p G.measure) : Prop :=
  ((x : α → ℂ) =ᵐ[G.measure] f)

/--
`y` is the Besov/Lp representative of the pointwise product `m * x`.

The multiplier definitions below use this relation instead of choosing a
particular representative for the product in the quotient space.
-/
def RepresentsPointwiseProduct
    (m : α → ℂ) (x y : Lp ℂ p G.measure) : Prop :=
  ((y : α → ℂ) =ᵐ[G.measure] fun z => m z * (x : α → ℂ) z)

variable [Fact (1 ≤ p)] [Fact (1 ≤ q)]

/--
A real number `C` is an operator bound for pointwise multiplication by `m` on
the Besov-ish space generated by `A`.

This is the formal version of saying that `f ↦ m f` is bounded on
`\mathcal B^s_{p,q}`.  The output is existential because multiplying an `L^p`
equivalence class by a concrete function is represented by an a.e. relation.
-/
def PointwiseMultiplierBound
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) (C : ℝ) : Prop :=
  0 ≤ C ∧
    ∀ x : BesovishSpace A q,
      ∃ y : BesovishSpace A q,
        RepresentsPointwiseProduct (G := G) (p := p) m
          (x : Lp ℂ p G.measure) (y : Lp ℂ p G.measure) ∧
        BesovishSpace.Norm_Costpq A q y ≤
          C * BesovishSpace.Norm_Costpq A q x

/--
Pointwise multiplication by `m` is a bounded multiplier on the Besov-ish space
generated by `A`.
-/
def IsPointwiseMultiplier
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) : Prop :=
  ∃ C : ℝ, PointwiseMultiplierBound (A := A) q m C

/--
The set of all admissible operator bounds for pointwise multiplication by `m`.
-/
def pointwiseMultiplierBoundSet
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) : Set ℝ :=
  { C | PointwiseMultiplierBound (A := A) q m C }

/--
The multiplier norm, as the infimum of all admissible operator bounds.

When no bound exists this is simply the order-theoretic infimum of the empty
set; the useful theorems below are stated under explicit boundedness
hypotheses.
-/
noncomputable def pointwiseMultiplierNorm
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) : ℝ :=
  sInf (pointwiseMultiplierBoundSet (A := A) q m)

/--
An `L^p` vector is represented by one atom of the family `A`.
-/
def RepresentsAtom (A : AtomFamily G s p u)
    (x : Lp ℂ p G.measure) : Prop :=
  ∃ (Q : WeakGridCell G) (φ : (A.localSpace Q).carrier),
    A.IsAtom Q φ ∧ RepresentsFunction (G := G) (p := p) (A.toFunction Q φ) x

/--
The atom tests used in the `selfs` condition.

The paper takes a supremum over Souza atoms.  Here we phrase the same idea in
the quotient model: an admissible test is a Besov-ish vector represented by an
atom and whose coefficient-cost gauge is at most one.
-/
def AtomicUnit
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (x : BesovishSpace A q) : Prop :=
  RepresentsAtom (G := G) (p := p) A (x : Lp ℂ p G.measure) ∧
    BesovishSpace.Norm_Costpq A q x ≤ 1

/--
A real number `C` bounds the Triebel-style `selfs` tests for `m`.

This packages the condition
`sup_a ‖m a‖_{B^s_{p,q}} ≤ C`, where `a` ranges over normalized atoms.
-/
def PointwiseSelfsBound
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) (C : ℝ) : Prop :=
  0 ≤ C ∧
    ∀ x : BesovishSpace A q,
      AtomicUnit (A := A) q x →
        ∃ y : BesovishSpace A q,
          RepresentsPointwiseProduct (G := G) (p := p) m
            (x : Lp ℂ p G.measure) (y : Lp ℂ p G.measure) ∧
          BesovishSpace.Norm_Costpq A q y ≤ C

/--
The set of all bounds for the `selfs` atom tests.
-/
def pointwiseSelfsBoundSet
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) : Set ℝ :=
  { C | PointwiseSelfsBound (A := A) q m C }

/--
The `selfs` seminorm: the infimum of all bounds for multiplying normalized
atoms by `m`.
-/
noncomputable def pointwiseSelfsNorm
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) : ℝ :=
  sInf (pointwiseSelfsBoundSet (A := A) q m)

/--
The Triebel-style `selfs` class from the paper.

It consists of functions that are themselves represented by a Besov-ish vector
and have a finite uniform atom-test bound.
-/
def PointwiseSelfsClass
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    (m : α → ℂ) : Prop :=
  (∃ x : BesovishSpace A q,
      RepresentsFunction (G := G) (p := p) m (x : Lp ℂ p G.measure)) ∧
    ∃ C : ℝ, PointwiseSelfsBound (A := A) q m C

/--
Every operator bound for a multiplier also bounds the `selfs` atom tests.

This is the formal version of the elementary inequality from the paper:
`|g|_{B^s_{p,q,selfs}} ≤ |g|_{M(B^s_{p,q})}`.
-/
theorem PointwiseMultiplierBound.selfsBound
    {A : AtomFamily G s p u} {m : α → ℂ} {C : ℝ}
    (hC : PointwiseMultiplierBound (A := A) q m C) :
    PointwiseSelfsBound (A := A) q m C := by
  rcases hC with ⟨hC_nonneg, hbound⟩
  refine ⟨hC_nonneg, ?_⟩
  intro x hx
  rcases hbound x with ⟨y, hprod, hy⟩
  refine ⟨y, hprod, ?_⟩
  calc
    BesovishSpace.Norm_Costpq A q y
        ≤ C * BesovishSpace.Norm_Costpq A q x := hy
    _ ≤ C * 1 := mul_le_mul_of_nonneg_left hx.2 hC_nonneg
    _ = C := by rw [mul_one]

/--
If `m` is a pointwise multiplier and is itself represented by a Besov-ish
vector, then `m` belongs to the `selfs` class.
-/
theorem pointwiseSelfsClass_of_isPointwiseMultiplier
    {A : AtomFamily G s p u} {m : α → ℂ}
    (hm : IsPointwiseMultiplier (A := A) q m)
    (hmem : ∃ x : BesovishSpace A q,
      RepresentsFunction (G := G) (p := p) m (x : Lp ℂ p G.measure)) :
    PointwiseSelfsClass (A := A) q m := by
  rcases hm with ⟨C, hC⟩
  exact ⟨hmem, ⟨C, hC.selfsBound⟩⟩

/--
Any concrete multiplier bound gives the same concrete upper bound for the
`selfs` seminorm.
-/
theorem pointwiseSelfsNorm_le_of_multiplierBound
    {A : AtomFamily G s p u} {m : α → ℂ} {C : ℝ}
    (hC : PointwiseMultiplierBound (A := A) q m C) :
    pointwiseSelfsNorm (A := A) q m ≤ C := by
  have hbdd : BddBelow (pointwiseSelfsBoundSet (A := A) q m) := by
    refine ⟨0, ?_⟩
    intro D hD
    exact hD.1
  exact csInf_le hbdd hC.selfsBound

omit [Fact (1 ≤ p)] in
/-- The zero vector represents the zero pointwise product. -/
theorem representsPointwiseProduct_zero
    (m : α → ℂ) :
    RepresentsPointwiseProduct (G := G) (p := p) m
      (0 : Lp ℂ p G.measure) (0 : Lp ℂ p G.measure) := by
  exact (Lp.coeFn_zero ℂ p G.measure).mono fun x hx => by
    have hx0 : ((0 : Lp ℂ p G.measure) : α → ℂ) x = 0 := by
      simpa using hx
    change ((0 : Lp ℂ p G.measure) : α → ℂ) x =
      m x * ((0 : Lp ℂ p G.measure) : α → ℂ) x
    rw [hx0]
    simp

omit [Fact (1 ≤ p)] in
/--
Pointwise-product representatives are compatible with addition in `L^p`.
-/
theorem RepresentsPointwiseProduct.add
    {m : α → ℂ} {x₁ x₂ y₁ y₂ : Lp ℂ p G.measure}
    (h₁ : RepresentsPointwiseProduct (G := G) (p := p) m x₁ y₁)
    (h₂ : RepresentsPointwiseProduct (G := G) (p := p) m x₂ y₂) :
    RepresentsPointwiseProduct (G := G) (p := p) m (x₁ + x₂) (y₁ + y₂) := by
  filter_upwards [Lp.coeFn_add y₁ y₂, Lp.coeFn_add x₁ x₂, h₁, h₂] with x hy hx hprod₁ hprod₂
  calc
    ((y₁ + y₂ : Lp ℂ p G.measure) : α → ℂ) x
        = ((y₁ : α → ℂ) + (y₂ : α → ℂ)) x := hy
    _ = m x * ((x₁ : α → ℂ) x) + m x * ((x₂ : α → ℂ) x) := by
        simp [Pi.add_apply, hprod₁, hprod₂]
    _ = m x * (((x₁ : α → ℂ) + (x₂ : α → ℂ)) x) := by
        simp [mul_add]
    _ = m x * (((x₁ + x₂ : Lp ℂ p G.measure) : α → ℂ) x) := by
        rw [hx]

omit [Fact (1 ≤ p)] in
/--
Pointwise-product representatives are compatible with complex scalar
multiplication in `L^p`.
-/
theorem RepresentsPointwiseProduct.smul
    {m : α → ℂ} {x y : Lp ℂ p G.measure} (c : ℂ)
    (h : RepresentsPointwiseProduct (G := G) (p := p) m x y) :
    RepresentsPointwiseProduct (G := G) (p := p) m (c • x) (c • y) := by
  filter_upwards [Lp.coeFn_smul c y, Lp.coeFn_smul c x, h] with z hy hx hprod
  calc
    ((c • y : Lp ℂ p G.measure) : α → ℂ) z
        = (c • (y : α → ℂ)) z := hy
    _ = c * (m z * (x : α → ℂ) z) := by
        simp [Pi.smul_apply, hprod]
    _ = m z * (c * (x : α → ℂ) z) := by ring
    _ = m z * ((c • (x : α → ℂ)) z) := by simp
    _ = m z * (((c • x : Lp ℂ p G.measure) : α → ℂ) z) := by
        rw [hx]

/--
The `selfs` bound controls scalar multiples of normalized atom tests.

This is the formal version of the estimate
`‖c · g a_Q‖ ≤ |c| C` used in the proof of
`M(B^s_{1,1}) = B^s_{1,1,selfs}`.
-/
theorem PointwiseSelfsBound.smul_atomicUnit
    {A : AtomFamily G s p u} {m : α → ℂ} {C : ℝ}
    (hC : PointwiseSelfsBound (A := A) q m C)
    (c : ℂ) (x : BesovishSpace A q)
    (hx : AtomicUnit (A := A) q x) :
    ∃ y : BesovishSpace A q,
      RepresentsPointwiseProduct (G := G) (p := p) m
        (c • (x : Lp ℂ p G.measure)) (y : Lp ℂ p G.measure) ∧
      BesovishSpace.Norm_Costpq A q y ≤ C * ‖c‖ := by
  rcases hC with ⟨hC_nonneg, hbound⟩
  rcases hbound x hx with ⟨y₀, hprod₀, hy₀⟩
  refine ⟨c • y₀, ?_, ?_⟩
  · simpa using hprod₀.smul c
  · calc
      BesovishSpace.Norm_Costpq A q (c • y₀)
          = ‖c‖ * BesovishSpace.Norm_Costpq A q y₀ := by
            rw [BesovishSpace.Norm_Costpq_smul_eq
              (A := A) (q := q) A.p_ne_top
              (BesovishSpace.hasFiniteCostRepresentations (A := A) q)]
      _ ≤ ‖c‖ * C := mul_le_mul_of_nonneg_left hy₀ (norm_nonneg c)
      _ = C * ‖c‖ := by ring

/--
Finite atomic-sum form of the `selfs ⇒ multiplier` argument.

If `m` satisfies the `selfs` atom test with bound `C`, then multiplying any
finite linear combination of normalized atom tests costs at most `C` times the
sum of the absolute coefficients.  This is the finite core of the paper's
proof of `M(B^s_{1,1}) = B^s_{1,1,selfs}`; the remaining step is to pass from
finite partial sums to an arbitrary finite-cost atomic representation.
-/
theorem PointwiseSelfsBound.finite_atomic_sum
    {A : AtomFamily G s p u} {m : α → ℂ} {C : ℝ}
    (hC : PointwiseSelfsBound (A := A) q m C)
    {ι : Type*} (S : Finset ι) (c : ι → ℂ) (x : ι → BesovishSpace A q)
    (hx : ∀ i ∈ S, AtomicUnit (A := A) q (x i)) :
    ∃ y : BesovishSpace A q,
      RepresentsPointwiseProduct (G := G) (p := p) m
        (∑ i ∈ S, c i • (x i : Lp ℂ p G.measure))
        (y : Lp ℂ p G.measure) ∧
      BesovishSpace.Norm_Costpq A q y ≤
        C * ∑ i ∈ S, ‖c i‖ := by
  classical
  rcases hC with ⟨hC_nonneg, hC_bound⟩
  induction S using Finset.induction_on with
  | empty =>
      refine ⟨0, ?_, ?_⟩
      · simpa using representsPointwiseProduct_zero (G := G) (p := p) m
      · have hzero :
          BesovishSpace.Norm_Costpq A q (0 : BesovishSpace A q) = 0 := by
          have hsmul := BesovishSpace.Norm_Costpq_smul_eq
            (A := A) (q := q) A.p_ne_top
            (BesovishSpace.hasFiniteCostRepresentations (A := A) q)
            (0 : ℂ) (0 : BesovishSpace A q)
          simp at hsmul
          exact hsmul
        simp [hzero]
  | insert a S ha ih =>
      have hxS : ∀ i ∈ S, AtomicUnit (A := A) q (x i) := by
        intro i hi
        exact hx i (Finset.mem_insert_of_mem hi)
      rcases ih hxS with ⟨yS, hprodS, hyS⟩
      have hxa : AtomicUnit (A := A) q (x a) :=
        hx a (Finset.mem_insert_self a S)
      rcases (PointwiseSelfsBound.smul_atomicUnit
        (A := A) (q := q) (m := m) (C := C)
        ⟨hC_nonneg, hC_bound⟩ (c a) (x a) hxa) with
        ⟨ya, hproda, hya⟩
      refine ⟨ya + yS, ?_, ?_⟩
      · have hprod_sum := hproda.add hprodS
        simpa [Finset.sum_insert ha] using hprod_sum
      · have htri :
          BesovishSpace.Norm_Costpq A q (ya + yS) ≤
            BesovishSpace.Norm_Costpq A q ya +
              BesovishSpace.Norm_Costpq A q yS :=
          BesovishSpace.Norm_Costpq_add_le
            (A := A) (q := q) A.p_ne_top
            (BesovishSpace.hasFiniteCostRepresentations (A := A) q) ya yS
        calc
          BesovishSpace.Norm_Costpq A q (ya + yS)
              ≤ BesovishSpace.Norm_Costpq A q ya +
                  BesovishSpace.Norm_Costpq A q yS := htri
          _ ≤ C * ‖c a‖ + C * ∑ i ∈ S, ‖c i‖ :=
              add_le_add hya hyS
          _ = C * ∑ i ∈ insert a S, ‖c i‖ := by
              rw [Finset.sum_insert ha]
              ring

/--
A level block with exactly one active atom.

The active cell has coefficient `1`; all other coefficients are zero.  This is
the Lean analogue of isolating one atomic term from a representation.
-/
private noncomputable def singleAtomLevelBlock
    (A : AtomFamily G s p u) {k : ℕ} (Q : LevelCell G k)
    (φ : (A.localSpace (levelCellToWeakGridCell G k Q)).carrier)
    (hφ : A.IsAtom (levelCellToWeakGridCell G k Q) φ) :
    LevelBlock A k where
  coeff := fun P => if P = Q then 1 else 0
  atom := fun P => by
    by_cases hP : P = Q
    · subst P
      exact φ
    · exact Classical.choose (A.atoms_nonempty_on (levelCellToWeakGridCell G k P))
  atom_mem := by
    intro P
    by_cases hP : P = Q
    · subst P
      simpa using hφ
    · simpa [hP] using
        Classical.choose_spec (A.atoms_nonempty_on (levelCellToWeakGridCell G k P))

omit [Fact (1 ≤ p)] in
/--
The single-atom level block represents the underlying atom as an `L^p`
function.
-/
private theorem singleAtomLevelBlock_representsFunction
    (A : AtomFamily G s p u) {k : ℕ} (Q : LevelCell G k)
    (φ : (A.localSpace (levelCellToWeakGridCell G k Q)).carrier)
    (hφ : A.IsAtom (levelCellToWeakGridCell G k Q) φ) :
    RepresentsFunction (G := G) (p := p)
      (A.toFunction (levelCellToWeakGridCell G k Q) φ)
      ((singleAtomLevelBlock A Q φ hφ).toLp A) := by
  classical
  let B := singleAtomLevelBlock A Q φ hφ
  refine (LevelBlock.coeFn_toLp A B).trans ?_
  refine Filter.Eventually.of_forall ?_
  intro x
  unfold LevelBlock.toFunLt
  rw [Finset.sum_eq_single Q]
  · simp [B, singleAtomLevelBlock]
  · intro P _ hPQ
    simp [B, singleAtomLevelBlock, hPQ]
  · intro hQ
    exact False.elim (hQ (by simp))

/--
The Besov-ish vector associated to one atom, for an arbitrary Besov `q`.
-/
private noncomputable def singleAtomBesovish
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    {k : ℕ} (Q : LevelCell G k)
    (φ : (A.localSpace (levelCellToWeakGridCell G k Q)).carrier)
    (hφ : A.IsAtom (levelCellToWeakGridCell G k Q) φ) :
    BesovishSpace A q :=
  ⟨(singleAtomLevelBlock A Q φ hφ).toLp A,
    levelBlock_toLp_mem_besovish (A := A) (q := q)
      (singleAtomLevelBlock A Q φ hφ)⟩

/--
The one-atom Besov-ish vector is represented by that atom.
-/
private theorem singleAtomBesovish_representsAtom
    (A : AtomFamily G s p u) (q : ℝ≥0∞) [Fact (1 ≤ q)]
    {k : ℕ} (Q : LevelCell G k)
    (φ : (A.localSpace (levelCellToWeakGridCell G k Q)).carrier)
    (hφ : A.IsAtom (levelCellToWeakGridCell G k Q) φ) :
    RepresentsAtom (G := G) (p := p) A
      (singleAtomBesovish A q Q φ hφ : Lp ℂ p G.measure) := by
  refine ⟨levelCellToWeakGridCell G k Q, φ, hφ, ?_⟩
  simpa [singleAtomBesovish] using
    singleAtomLevelBlock_representsFunction (G := G) (p := p) A Q φ hφ

private instance instFactOneLeOneENNReal : Fact (1 ≤ (1 : ℝ≥0∞)) :=
  ⟨le_rfl⟩

/--
The coefficient power of the one-atom representation is concentrated at the
atom's level and is equal to `1` there, in the endpoint `p = 1`.
-/
private theorem singleAtomLevelBlock_levelCoeffPower_one
    (A : AtomFamily G s (1 : ℝ≥0∞) u) {k : ℕ} (Q : LevelCell G k)
    (φ : (A.localSpace (levelCellToWeakGridCell G k Q)).carrier)
    (hφ : A.IsAtom (levelCellToWeakGridCell G k Q) φ) :
    ∀ n : ℕ,
      (LpGridRepresentation.singleBlockRepresentation
        (G := G) (A := A) (singleAtomLevelBlock A Q φ hφ)).levelCoeffPower n =
        if n = k then 1 else 0 := by
  classical
  intro n
  by_cases hn : n = k
  · subst n
    rw [LpGridRepresentation.singleBlockRepresentation_levelCoeffPower_self]
    rw [Finset.sum_eq_single Q]
    · simp [singleAtomLevelBlock]
    · intro P _ hPQ
      simp [singleAtomLevelBlock, hPQ]
    · intro hQ
      exact False.elim (hQ (by simp))
  · unfold LpGridRepresentation.levelCoeffPower LpGridRepresentation.singleBlockRepresentation
    simp [hn, LevelBlock.zero]

end

end WeakGridSpace

namespace GoodGridSpace

universe u

variable {α : Type u} [MeasurableSpace α]

noncomputable section

/--
Pointwise multiplier bound specialized to the Souza atom Besov space on a good
grid.
-/
abbrev SouzaPointwiseMultiplierBound
    (G : GoodGridSpace (α := α)) (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (m : α → ℂ) (C : ℝ) : Prop :=
  WeakGridSpace.PointwiseMultiplierBound
    (A := souzaAtomFamily G s p hs hp hp_top) q m C

/--
Pointwise multipliers of the Souza Besov space associated to a good grid.
-/
abbrev SouzaPointwiseMultiplier
    (G : GoodGridSpace (α := α)) (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (m : α → ℂ) : Prop :=
  WeakGridSpace.IsPointwiseMultiplier
    (A := souzaAtomFamily G s p hs hp hp_top) q m

/--
The `selfs` atom-test class for the Souza Besov space on a good grid.
-/
abbrev SouzaPointwiseSelfsClass
    (G : GoodGridSpace (α := α)) (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (m : α → ℂ) : Prop :=
  WeakGridSpace.PointwiseSelfsClass
    (A := souzaAtomFamily G s p hs hp hp_top) q m

/--
The `selfs` seminorm specialized to Souza atoms on a good grid.
-/
noncomputable abbrev souzaPointwiseSelfsNorm
    (G : GoodGridSpace (α := α)) (s : ℝ) (p q : ℝ≥0∞)
    (hs : 0 < s) (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    [Fact (1 ≤ p)] [Fact (1 ≤ q)]
    (m : α → ℂ) : ℝ :=
  WeakGridSpace.pointwiseSelfsNorm
    (A := souzaAtomFamily G s p hs hp hp_top) q m

end

end GoodGridSpace
